Updated makefile
Signed-off-by: Soumya Ghosh Dastidar <gdsoumya@gmail.com>

diff --git a/litmus-portal/Makefile b/litmus-portal/Makefile
--- a/litmus-portal/Makefile
+++ b/litmus-portal/Makefile
@@ -60,49 +60,68 @@ litmus-portal-push:
 	@echo "------------------"
 	@echo "--> Push frontend and backend images" 
 	@echo "------------------"
-	REPONAME=$(REPONAME) IMGNAME=$(FRONTEND_IMAGE) IMGTAG=$(IMGTAG) bash ../hack/push
-	REPONAME=$(REPONAME) IMGNAME=$(GRAPHQL_SERVER_IMAGE) IMGTAG=$(IMGTAG) bash ../hack/push
-	REPONAME=$(REPONAME) IMGNAME=$(SUBSCRIBER_IMAGE) IMGTAG=$(IMGTAG) bash ../hack/push
-	REPONAME=$(REPONAME) IMGNAME=$(AUTHENTICATION_SERVER_IMAGE) IMGTAG=$(IMGTAG) bash ../hack/push
-	REPONAME=$(REPONAME) IMGNAME=$(SELF_DEPLOYER_IMAGE) IMGTAG=$(IMGTAG) bash ../hack/push
+	REPONAME=$(REPONAME) IMGNAME=$(FRONTEND_IMAGE) IMGTAG=$(IMGTAG) ../hack/push
+	REPONAME=$(REPONAME) IMGNAME=$(GRAPHQL_SERVER_IMAGE) IMGTAG=$(IMGTAG) ../hack/push
+	REPONAME=$(REPONAME) IMGNAME=$(SUBSCRIBER_IMAGE) IMGTAG=$(IMGTAG) ../hack/push
+	REPONAME=$(REPONAME) IMGNAME=$(AUTHENTICATION_SERVER_IMAGE) IMGTAG=$(IMGTAG) ../hack/push
+	REPONAME=$(REPONAME) IMGNAME=$(SELF_DEPLOYER_IMAGE) IMGTAG=$(IMGTAG) ../hack/push
 
 
 .PHONY: litmus-portal-check
-litmus-portal-check : lint-checks unused-package-check
+litmus-portal-check : npm-install lint-checks unused-package-check
+
+npm-install:
+	@echo "------------------"
+	@echo "--> checking code style [frontend]"
+	@echo "------------------"
+	cd frontend && npm i
 
 lint-checks:
+# 	@echo "------------------"
+# 	@echo "--> checking code style [frontend]"
+# 	@echo "------------------"
+# 	cd frontend && npm run lint
+
 	@echo "------------------"
-	@echo "--> checking code style"
+	@echo "--> checking code style [backend]"
 	@echo "------------------"
 	@fmtRes=$$(gofmt -d $$(find . -path ./vendor -prune -o -name '*.go' -print)); \
 	if [ -n "$${fmtRes}" ]; then \
-		echo "gofmt checking failed!"; echo "$${fmtRes}"; echo; \
-		echo "Please ensure you are using $$($(GO) version) for formatting code."; \
+		echo "gofmt checking failed!" && echo "$${fmtRes}" \
+		&& echo "Please ensure you are using $$($(GO) version) for formatting code." \
+		&& exit 1;\
 	fi
 
 unused-package-check:
+# 	@echo "------------------"
+# 	@echo "--> Check litmus-portal frontend [depcheck]"
+# 	@echo "------------------"
+# 	cd frontend && npm i depcheck --no-save && node_modules/.bin/depcheck --skip-missing .
+
 	@echo "------------------"
 	@echo "--> Check litmus-portal backend [go mod tidy]"
 	@echo "------------------"
 	@tidyRes=$$(cd backend/graphql-server && go mod tidy); \
 	if [ -n "$${tidyRes}" ]; then \
-		echo "go mod tidy checking failed!"; echo "$${tidyRes}"; echo; \
-		echo "Please ensure you are using $$($(GO) version) for formatting code."; \
+		echo "go mod tidy checking failed!" && echo "$${tidyRes}" \
+		&& echo "Please ensure you are using $$($(GO) version) for formatting code." \
+		&& exit 1; \
 	fi
 	@echo "------------------"
 	@echo "--> Check litmus-portal auth [go mod tidy]"
 	@echo "------------------"
 	@tidyRes=$$(cd backend/auth && go mod tidy); \
 	if [ -n "$${tidyRes}" ]; then \
-		echo "go mod tidy checking failed!"; echo "$${tidyRes}"; echo; \
-		echo "Please ensure you are using $$($(GO) version) for formatting code."; \
+		echo "go mod tidy checking failed!" && echo "$${tidyRes}" \
+		&& echo "Please ensure you are using $$($(GO) version) for formatting code." \
+		&& exit 1; \
 	fi
-	
+
 .PHONY: litmus-portal-test
-litmus-portal-test : frontend-unit-test
+litmus-portal-test : npm-install frontend-unit-test
 
 frontend-unit-test:
 	@echo "------------------"
 	@echo "--> Frontend Unit Test"
 	@echo "------------------"
-	cd ./frontend && npm i && npx cypress run
+	cd ./frontend && npx cypress run
