Added gh-actions for event-tracker
Signed-off-by: Jonsy13 <vedant.shrotria@harness.io>

diff --git a/chaoscenter/Makefile b/chaoscenter/Makefile
--- a/chaoscenter/Makefile
+++ b/chaoscenter/Makefile
@@ -78,15 +78,15 @@ backend-services-checks:
 		&& echo "Please ensure you are using $$($(GO) version) for formatting code" \
 		&& exit 1; \
 	fi
-	# @echo "------------------"
-	# @echo "--> Check chaos-center event tracker [go mod tidy]"
-	# @echo "------------------"
-	# @tidyRes=$$(cd cluster-agents/event-tracker && go mod tidy); \
-	# if [ -n "$${tidyRes}" ]; then \
-	# 	echo "go mod tidy checking failed!" && echo "$${tidyRes}" \
-	# 	&& echo "Please ensure you are using $$($(GO) version) for formatting code" \
-	# 	&& exit 1; \
-	# fi
+	@echo "------------------"
+	@echo "--> Check chaos-center event tracker [go mod tidy]"
+	@echo "------------------"
+	@tidyRes=$$(cd cluster-agents/event-tracker && go mod tidy); \
+	if [ -n "$${tidyRes}" ]; then \
+		echo "go mod tidy checking failed!" && echo "$${tidyRes}" \
+		&& echo "Please ensure you are using $$($(GO) version) for formatting code" \
+		&& exit 1; \
+	fi
 	# @echo "------------------"
 	# @echo "--> Check chaos-center upgrade agent [go mod tidy]"
 	# @echo "------------------"
